---
title: "Quality pipeline brainstorming"
author: "Liam D. Bailey & Stefan Vriend"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Checks can be split into two separate groups: data quality checks and pipeline output checks.

# Data quality checks

These are checks to ensure that the provided data meet biological and data management expectations. Checks will include:

* Clutch size <= brood size <= number of fledglings (N.B. May actually differ because of clutch manipulation). Error: If no evidence of experimentation and this assumption is violated. Warning: If there is evidence of cohort manipulation and this assumption is violated.

* Clutch/Brood/Fledglings should be integers

* Laying date < Hatch date < Fledge date

* Check for impossible values in everything (have range for warnings and range for errors) (NOT NOW).
  *EggMass/ChickMass/AdultMass/ChickTarsus/AdultTarsus/ChickWinglength/AdultWingLength:
  *max Clutch/max Brood/max FledgeSize:
  *Age:
  *Laying date: THIS IS POPULATION SPECIFIC WE NEED TO THINK HOW TO DEAL WITH THIS.
  *min Incubation time/min hatch - fledge time:
  
* Error in clutch size/laying date etc. is reasonable (NOT NOW).

* Test for normality/Poisson (return a warning if fail) (NOT NOW).

* Plot histogram to show distribution of traits (and show warning and error ranges) (NOT NOW).

* When new data are added, mean and SD of the data should not change substantially (only test this locally so that we don't store mean and SD data) (NOT NOW!)

* SampleYear cannot be later than the current year (we can't get data from the future...yet), or earlier than the year the study started.

* BroodID/IndividualID/NestBoxID are unique.

* No conflicting sex.

* Number of ringed chicks associated (i.e. records in capture data) should match brood size.
Might be fairly common. Could make it >2 chick difference?

* Every individual that is a parent of a brood must have a capture record.

* Every individual with a capture record must have an individual record.

* Every BroodID of an individual has to be in the brood data table.

* Return a list of columns that are not filled (warnings) (NOT NOW).

* Individual cannot be captured before it was a chick.
  
# Pipeline output checks

These are checks that checks for bugs in the output of the pipeline.

* *Do the data formats match the standard protocol?*

  
  
