#' Construct standard format for data from Glimmen, the Netherlands
#'
#' A pipeline to produce the standard format for the study site at
#' Glimmen, the Netherlands, administred by Simon Verhulst (University of Groningen).
#'
#' This pipeline is built using SPI-Birds' \href{https://github.com/SPI-Birds/documentation/blob/master/standard_protocol/SPI_Birds_Protocol_v2.0.0.pdf}{standard format v2.0.0}.
#'
#' This section provides details on data management choices that are unique to these data.
#'
#' \strong{speciesID}: Species are not explicitly recorded, but we assume that all individuals are successfully identified as Eurasian jackdaws.
#'
#' \strong{observedClutchSize}: Broods with less than 0 eggs are excluded. Check with data owner.
#'
#' @inheritParams pipeline_params
#'
#' @return Generates either 6 .csv files or 6 data frames in the standard format (v2.0.0).
#'
#' @export
#'

format_GLI <- function(db = choose_directory(),
                       species = NULL,
                       site = NULL,
                       optional_variables = NULL,
                       path = ".",
                       output_type = "R") {

  # Force choose_directory() if used
  force(db)

  # Assign species for filtering
  if(is.null(species)) {

    species <- species_codes$speciesID

  }

  # If all optional variables are requested, retrieve all names
  if(!is.null(optional_variables) & "all" %in% optional_variables) optional_variables <- names(unlist(unname(utility_variables)))

  # Record start time to provide processing time to the developer & user
  start_time <- Sys.time()

  # Load data
  message("Importing primary data...")

  all_data <- readxl::read_excel(path = paste0(db, "/GLI_PrimaryData.xlsx")) %>%
    # Convert all column names to snake case
    janitor::clean_names() %>%
    dplyr::mutate(siteID = "GLI",
                  # Ensure unique plotIDs; add siteID as prefix
                  # TODO: Check whether 'colony' is interpreted correctly
                  plotID = paste0("GLI_", .data$colony)) %>%
    # We assume that all records are successfully identified as Eurasian jackdaws
    dplyr::mutate(speciesID = species_codes$speciesID[species_codes$speciesCode == "10015"]) %>%
    # Convert dates
    dplyr::mutate(dplyr::across(.cols = c("ld", "hd"),
                                .fns = ~{

                                  as.Date(.x)

                                })) %>%
    # Filter species
    dplyr::filter(.data$speciesID %in% {species})

  # BROOD DATA
  message("Compiling brood data...")

  Brood_data <- create_brood_GLI(data = all_data,
                                 optional_variables = optional_variables)

  # CAPTURE DATA
  message("Compiling capture data...")

  Capture_data <- create_capture_GLI(brood_data = Brood_data,
                                     optional_variables = optional_variables)


}

#' Create brood data table for Glimmen, the Netherlands.
#'
#' Create brood data table in the standard format (v2.0.0) for data from Glimmen, the Netherlands.
#'
#' @param data Data frame. Primary data from Glimmen, the Netherlands.
#' @param optional_variables A character vector of names of optional variables (generated by standard utility functions) to be included in the pipeline output.
#'
#' @return A data frame.
#'

create_brood_GLI <- function(data,
                             optional_variables) {

  broods <- data %>%
    dplyr::rename(broodID = "jd_nest",
                  femaleID = "fem_id",
                  maleID = "male_id",
                  observedLayDate = "ld",
                  observedClutchSize = "cs",
                  observedHatchDate = "hd") %>%
    # Remove broods with observedClutchSize < 0
    # TODO: Check with data owner
    dplyr::filter(.data$observedClutchSize >= 0 | is.na(.data$observedClutchSize)) %>%
    # femaleID & maleID are unique numbers, except when negative then:
    # -1: unringed individual
    # -2: ringed but unidentified individual
    # -3: unknown
    # As these codes are not unique, we cannot use them to identify individuals,
    # so in these cases we set femaleID/maleID to NA.
    # When femaleID/maleID is non-NA add site prefix (GLI) to ensure that IDs are unique across SPI-Birds' study sites
    dplyr::mutate(dplyr::across(.cols = c("femaleID", "maleID"),
                                .fns = ~{

                                  dplyr::case_when(.x < 0 ~ NA_character_,
                                                   TRUE ~ paste0("GLI_", .x))

                                }),
                  observedLayYear = as.integer(lubridate::year(.data$observedLayDate)),
                  observedLayMonth = as.integer(lubridate::month(.data$observedLayDate)),
                  observedLayDay = as.integer(lubridate::day(.data$observedLayDate)),
                  observedHatchYear = as.integer(lubridate::year(.data$observedHatchDate)),
                  observedHatchMonth = as.integer(lubridate::month(.data$observedHatchDate)),
                  observedHatchDay = as.integer(lubridate::day(.data$observedHatchDate)))

  # Add optional variables
  output <- broods %>%
    {if("breedingSeason" %in% optional_variables) calc_season(data = ., season = .data$year) else .} %>%
    # calculatedClutchType cannot be provided as number of fledglings are not recorded
    #{if("calculatedClutchType" %in% optional_variables) calc_clutchtype(data = ., na.rm = FALSE, protocol_version = "1.2") else .} %>%
    {if("nestAttemptNumber" %in% optional_variables) calc_nestattempt(data = ., season = .data$breedingSeason) else .}

  return(output)

}

#----------------------#
#TODO: Does Colony correspond with plotID?
#TODO: Is there location information (locationIDs and geographic coordinates)?
#TODO: What does Status  mean?
#TODO: How to interpret broods with LD and CS == 0?
#TODO: How to interpret broods with LD == NA and CS == 0
#TODO: How to interpret broods with CS < 0?
