quality_check_description_pdf <- "

\\section{Introduction}

Welcome to the SPI-Birds quality check report. This report shows the results of a number of standard data quality checks that can be
used on any data that have been created following the \\href{https://github.com/SPI-Birds/documentation/blob/master/standard_protocol/SPI_Birds_Protocol_v1.0.0.pdf}{SPI-Birds Standard Protocol}.

\\subsection{How to use this report}

All checks either look for 'potential errors' (values that we believe are impossible e.g. negative values) or 'warnings' (values that we believe are unlikely).
Checks are run on the four tables described in the SPI-Birds Standard Protocol: Brood data, Capture data, Individual data, and Location data.
These checks generally work on individual rows (but see the list of checks below).
When a 'warning' or 'potential error' is identified a line will be included in the report with information on the type of check that was violated
and the \\emph{row number} of the corresponding record. The \\emph{row number} refers to the column \\emph{Row} in the corresponding
table output in the standard format. It does \\textbf{not} refer to row numbers in the primary data. In addition, during the process of the quality
check two new columns ('warning' and 'error') will be added to each of the four data tables to allow potentially spurious records
to be easily identified.

\\subsection{Verification of flagged records}

Some of the records flagged as a 'warning' or 'potential error' are likely to be uncommon but true observations. We don't want these same values to be flagged each time a new quality check is conducted. To overcome this, we have implemented an 'approve-listing' procedure that will prevent true records, that have been verified by the data owner, from appearing in future quality check reports. These records are listed at the end of this document. We hope that this will make the quality check reports more useful for data owners and users.

\\subsection{Check descriptions}

Brood checks:
  \\begin{itemize}
\\item \\textbf{B1}. Identify any empty columns (i.e. where all records are NA) in Brood data and return a 'warning'.
It is possible for empty columns to occur and this check will simply flag these empty columns so they can easily be identified by users.
\\item \\textbf{B2}. Compare clutch size and brood size. Clutch size is expected to be larger or equal to brood size. Broods that do not meet this expectation are flagged as 'warning' (in case they were experimentally manipulated) or 'potential error' (in case they were not experimentally manipulated).
\\item \\textbf{B3}. Compare brood size and number of fledglings. Brood size is expected to be larger or equal to number of fledglings. Broods that do not meet this expectation are flagged as 'warning' (in case they were experimentally manipulated) or 'potential error' (in case they were not experimentally manipulated).
\\item \\textbf{B4}. Compare lay date and hatch date. Lay date is expected to be earlier than hatch date. Broods that do not meet this expectation are flagged as 'potential error'.
\\item \\textbf{B5}. Compare hatch date and fledge date. Hatch date is expected to be earlier than fledge date. Broods that do not meet this expectation are flagged as 'potential error'.
\\item \\textbf{B6a-c}. Compare clutch size (a), brood size (b), and number of fledglings (c) against reference values. Reference values are generated by population- and species-specific data if the number of observations is sufficiently large (n >= 100). Records are flagged as 'warning' if they are larger than the 99th percentile. Records are flagged as 'potential error' if they are negative or larger than 4 times the 99th percentile.
\\item \\textbf{B6d}. Compare lay date against reference values. Reference values are generated by population- and species-specific data if the number of observations is sufficiently large (n >= 100). Records are flagged as 'warning' if they are earlier than the 1st percentile or later than the 99th percentile. Records are flagged as 'potential error' if they are earlier than January 1st or later than December 31st of the same year.
\\item \\textbf{B7}. Compare brood size and the number of chicks recorded in Capture data. These numbers are expected to be equal. Records where brood size is larger than the number of recorded chicks are flagged as 'warning', as some chicks might have died before ringing. Records where brood size is smaller than the number of recorded chicks are flagged as 'potential error'.
\\item \\textbf{B8}. Check that brood identities (BroodID) are unique within populations. BroodIDs are not expected to be unique among populations. Records with non-unique BroodIDs are flagged as 'potential error'.
\\item \\textbf{B9}. Check that the order of clutch types per breeding female per breeding season is correct. Replacement and second clutches can occur in any order but never before first clutches. First clutches that are not listed first are flagged as 'potential error'.
\\item \\textbf{B10}. Compare species of mother and father. The species of the parents are expected to be the same in the majority of broods. Common, biologically possible multi-species broods are flagged as 'warning'. Other combinations are flagged as 'potential error'.
\\item \\textbf{B11}. Compare species of parents and the brood itself. The species of the parents and their brood are expected to be the same. Broods with a combination of species for which brood fostering is known to exist are flagged as 'warning'. Other combinations of species are flagged as 'potential error'.
\\item \\textbf{B12}. Compare species of brood and the chicks in the brood. The species of the brood and the chicks are expected to be the same. Broods with a combination of species for which brood fostering is known to exist are flagged as 'warning'. Other combinations of species are flagged as 'potential error'.
\\item \\textbf{B13}. Check that the sex of the mother is female. Broods where mothers are listed as male are flagged as 'potential error'.
\\item \\textbf{B14}. Check that the sex of the father is male. Broods where fathers are listed as female are flagged as 'potential error'.
\\end{itemize}

Capture checks:
  \\begin{itemize}
\\item \\textbf{C1}. Identify any empty columns (i.e. where all records are NA) in Capture data and return a 'warning'.
It is possible for empty columns to occur and this check will simply flag these empty columns so they can easily be identified by users.
\\item \\textbf{C2a-b}. Compare mass (a) and tarsus (b) against reference values. Reference values for mass in adults and tarsus in both adults and chicks are generated by population- and species-specific data if the number of observations is sufficiently large (n >= 100). Reference values for mass in chicks are either generated for each age using a logistic growth model or, if that fails, per age if the number of observations is sufficiently large (n >= 100). Records are flagged as 'warning' if they are smaller than the 1st percentile or larger than the 99th percentile. Records are flagged as 'potential error' if they are negative or larger than 4 times the 99th percentile.
\\item \\textbf{C3}. Check that the chick age values (in number of days since hatching) are within the expected duration of the nesting period. Expected number of days are between 0 and 30. Values outside this range are flagged as 'potential error'. Impossible chick age may be caused by problems with hatch date.
\\item \\textbf{C4}. Check that the adults captured on a nest are listed as the parents of that nest in Brood data. Adults that are not marked as the parents of the nest are flagged as 'warning'. This flag might occur for instance when the capture location of the nest encompasses more area than just the nest or when there are capture events outside the breeding season.
\\item \\textbf{C5}. Check that the observed age of chronologically ordered captures of an individual is correct. The age recorded in an individual's subsequent capture is expected to be equal when the capture was in the same year or larger when the capture was in a later year. Records of an individual caught as an adult before records of the same individual caught as a chick are flagged as 'potential error'. Other records where the observed age of a capture is larger than the age of a subsequent capture are flagged as 'warning'.
\\end{itemize}

Individual checks:
  \\begin{itemize}
\\item \\textbf{I1}. Identify any empty columns (i.e. where all records are NA) in Individual data and return a 'warning'.
It is possible for empty columns to occur and this check will simply flag these empty columns so they can easily be identified by users.
\\item \\textbf{I2}. Check that individual identities (IndvID) are unique within populations. IndvIDs are not expected to be unique among populations. Records with non-unique IndvIDs are flagged as 'potential error'.
\\item \\textbf{I3}. Check that the brood identities for an individual (BroodIDLaid, BroodIDFledged) match the correct nest in Capture data. Chicks caught on a nest that are not associated with corresponding brood identities are flagged as 'potential error'.
\\item \\textbf{I4}. Check for the uncertainty in the sex of an individual. Individuals that have been recorded as both male and female in Capture data are marked as conflicted ('C') by the pipeline and flagged as 'potential error'.
\\item \\textbf{I5}. Check for the uncertainty in the species of an individual. Individuals that have been recorded as different species in Capture data are marked as conflicted ('CCCCCC') by the pipeline and flagged as 'potential error'.
\\item \\textbf{I6}. Check that individuals in Individual data also appear in Capture data. Individual data are usually a direct product of Capture data, so this should never occur. If it does occur, it is an indication of problems in the underlying pipeline. Missing individuals are flagged as 'potential error'.
\\end{itemize}

Location checks:
  \\begin{itemize}
\\item \\textbf{L1}. Identify any empty columns (i.e. where all records are NA) in Location data and return a 'warning'.
It is possible for empty columns to occur and this check will simply flag these empty columns so they can easily be identified by users.
\\end{itemize}"

quality_check_titlepage_pdf <- "\\renewcommand{\\familydefault}{\\sfdefault}
\\begin{titlepage}
	\\centering % Center everything on the title page
	\\scshape % Use small caps for all text on the title page
	\\vspace*{1.5\\baselineskip} % White space at the top of the page
% ===================
%	Title Section
% ===================

	\\rule{13cm}{1.6pt}\\vspace*{-\\baselineskip}\\vspace*{2pt} % Thick horizontal rule
	\\rule{13cm}{0.4pt} % Thin horizontal rule

		\\vspace{0.75\\baselineskip} % Whitespace above the title
% ========== Title ===============
	{	\\Huge SPI-Birds Quality Check\\\\}
% ======================================
		\\vspace{0.75\\baselineskip} % Whitespace below the title
	\\rule{13cm}{0.4pt}\\vspace*{-\\baselineskip}\\vspace{3.2pt} % Thin horizontal rule
	\\rule{13cm}{1.6pt} % Thick horizontal rule

		\\vspace{0.75\\baselineskip} % Whitespace after the title block

% =================
%	Version number
% =================

    \\vspace{3mm}

    \\today

    \\vspace{1.25\\baselineskip}

% =================
%	Information
% =================
	{\\large Produced by: SPI-Birds team \\\\(Antica Culina, Liam D. Bailey, Chlo\\'e R. Nater, \\\\Stefan J.G. Vriend, Zuzana Zajkov\\'a \\& Marcel E. Visser)} \\\\
	\\vfill
\\end{titlepage}"

quality_check_description_html <- "



"

############################################################################

#' Parameter documentation for all pipelines
#'
#'@param db Location of database file.
#'@param species Species of interest. The 6 letter codes of all the species of
#'  interest as listed in the
#'  \href{https://github.com/SPI-Birds/documentation/blob/master/standard_protocol/SPI_Birds_Protocol_v1.0.0.pdf}{standard
#'  protocol}. If blank will return all major species.
#'@param pop The three-letter code of population as listed in the \href{https://github.com/SPI-Birds/documentation/blob/master/standard_protocol/SPI_Birds_Protocol_v1.0.0.pdf}{standard
#'  protocol}. For data owners with multiple populations (e.g. NIOO, UAN) where a single
#'  pipeline is used for many populations this argument is used to extract data from
#'  individual populations. For other pipelines that contain only one population
#'  this argument can be ignored.
#'@param path Location where output csv files will be saved.
#'@param output_type Should the pipeline generate .csv files ('csv') or R objects ('R').
#'
#'@name pipeline_params
NULL


#' Parameter documentation for brood data checks
#'
#' @param Brood_data Data frame. Brood data output from pipeline.
#' @param approved_list List object. List of approved records from brood_approved_list.csv,
#' capture_approved_list.csv, individual_approved_list.csv, location_approved_list.csv
#'
#'@name checks_brood_params
NULL

#' Parameter documentation for capture data checks
#'
#' @param Capture_data Data frame. Capture data output from pipeline.
#' @param approved_list List object. List of approved records from brood_approved_list.csv,
#' capture_approved_list.csv, individual_approved_list.csv, location_approved_list.csv
#'
#'@name checks_capture_params
NULL

#' Parameter documentation for individual data checks
#'
#' @param Individual_data Data frame. Individual data output from pipeline.
#' @param approved_list List object. List of approved records from brood_approved_list.csv,
#' capture_approved_list.csv, individual_approved_list.csv, location_approved_list.csv
#'
#'@name checks_individual_params
NULL

#' Parameter documentation for location data checks
#'
#' @param Location_data Data frame. Location data output from pipeline.
#' @param approved_list List object. List of approved records from brood_approved_list.csv,
#' capture_approved_list.csv, individual_approved_list.csv, location_approved_list.csv
#'
#'@name checks_location_params
NULL

#' Return documentation for data checks
#'
#' @return
#' A list of:
#' \item{CheckList}{A summary dataframe of check warnings and errors.}
#' \item{WarningRows}{A vector of rows with warnings.}
#' \item{ErrorRows}{A vector of rows with errors.}
#' \item{Warnings}{A list of row-by-row warnings.}
#' \item{Errors}{A list of row-by-row errors.}
#' @name checks_return
NULL

############################################################################

utils::globalVariables(c(".", "AvgChickTarsus", "AvgChickMass", "AvgTarsus", "PopID",
                         "CapturePlot", "ReleasePlot", "CapturePopID", "ReleasePopID",
                         "Weight", "Wing", "Mass",
                         "BroodID", "RingSeries", "Time", "LayDate",
                         "ClutchSize", "HatchDate", "variable",
                         "IndvID", "Species", "BreedingSeason",
                         "Age_observed", "Sex", "CaptureDate", "CaptureTime",
                         "Year", "Age", "BroodIDLaid", "BroodIDFledged",
                         "FirstYr", "RingAge", "Age_calculated",
                         "RingSeason", "Age_obsv", "FirstBroodID",
                         "LocationID", "FirstYear", "Aukko", "Malli",
                         "NestboxID", "LocationType", "Latitude",
                         "Longitude", "StartSeason", "EndSeason",
                         "Habitat", "GBPL", "Y_deg", "X_deg",
                         "YEARFIRST", "YEARLAST", "HasCoords",
                         "LeftTarsusLength", "Day", "Month", "CatchDate",
                         "Pop_name", "year", "site", "Plot", "box_number",
                         "March1Date", "first_egg_lay_date",
                         "egg_weight", "number_eggs_weighed", "final_clutch_size",
                         "weigh_date", "actual_hatch_date",
                         "actual_male_trapping_date", "actual_female_trapping_date",
                         "male_id", "female_id", "actual_pullus_ringing_date",
                         "number_fledged", "Species_codes", "BroodId",
                         "Ring", "JulianDate", "ChickAge",
                         "TrapingMethod", "Box", "NumberFledgedError",
                         "AvgEggMass", "OriginalTarsusMethod",
                         "ExperimentID", "Name", "ID", "Area", "AreaGroup",
                         "UserPlaceName", "AreaID", "SpeciesID",
                         "Description", "GeneticBroodID", "Sexe",
                         "RingYear", "RingNumber", "Individual",
                         "CaptureLocation", "species_pb",
                         "BroodIDRinged", "ReleaseLocation", "CaptureType",
                         "CaptureID", "Wing_Length", "MinAge", "BroodSpecies",
                         "BroodLocationID", "BroodLocation", "BroodYear", "RingNumberFemale",
                         "RingNumberMale", "LayDate", "LayDateDeviation",
                         "NumberHatched", "NumberHatchedDeviation",
                         "FledgeDate", "NumberFledged", "NumberFledgedDeviation",
                         "BroodSizeError", "NumberFledgedError",
                         "LayDateError", "BroodSize", "BroodSizeError",
                         "ClutchSizeError",
                         "NumberFledgedError", "SampleYear", "Mar1",
                         "Female_ring", "Male_ring", "ClutchType_observed",
                         "ClutchType_calc", "ClutchType_calculated",
                         "CluthcSizeError", "HatchDateError", "ExperimentID",
                         "Location", "StartYear", "EndYear",
                         "Row", "Ld", "Cs", "Hd", "Hs", "Fs",
                         "FId", "MId", "NestId", "HabitatOfRinging",
                         "YCoord", "XCoord", "Code", "NrEgg", "NrChickMass",
                         "FAge", "MAge", "Chick1Id", "Chick13Id",
                         "NN", "SOORT", "GB", "PL", "LD", "JAE",
                         "AE", "AEN", "NP", "PD", "PU", "LO",
                         "TY", "RM", "RW", "AW", "WD", "WU", "ME",
                         "GN", "GT", "GG", "CON", "SA", "NNN1", "NNN2",
                         "NNN3", "NNBI", "NNTRI", "VERL",
                         "coorx", "coory", "comm", "year", "gbpl",
                         "RN", "NRN", "KLR", "NKLR", "TAGTY",
                         "TAG", "NTAG", "GS", "VD", "LT", "VW",
                         "VLL", "GEW", "UUR", "TA", "BL", "BH",
                         "DMVL", "BLOED", "RUI", "COMM", "RECNUM",
                         "SPLOT", "TANEW", "TEEK", "klr_old",
                         "soort", "rn", "sex", "gbj", "cbj",
                         "gb", "vd", "nrn", "pit", "pitdate",
                         "klr1", "klr1date",
                         "klr2", "klr2date",
                         "klr3", "klr3date",
                         "klr4", "klr4date",
                         "molsex", "vll_med", "vll_n",
                         "cta_med", "cta_n", "ctanew_med",
                         "ctanew_n", "tarsus_med",
                         "tarsus_n", "tarsus_ty",
                         "%T>%", "Age_calc", "COORX", "COORY",
                         "FemaleID", "FledgeDateError", "GT_dist_gg",
                         "MaleID", "NestBoxType", "NrChickTarsus", "NumberChicksMass",
                         "NumberChicksTarsus", "NumberEggs", "SPLIT", "Tarsus",
                         "WingLength", "cgj", "chick_ids", "clutch_size",
                         "code", "data", "experiment", "father", "female_ring",
                         "group", "hatch_date", "hatching_date", "lat", "latitude",
                         "lay_date", "laying_date", "legacy_april_hatch_date",
                         "legacy_average_egg_weight", "legacy_mean_fledge_weight",
                         "long", "longitude", "male_ring", "mean_chick_weight",
                         "mother", "nest", "nest_box", "nestbox", "num_chicks",
                         "num_chicks_ringed", "num_eggs_weighed", "num_fledglings",
                         "number_hatched", "owner", "plot", "pop_names",
                         "py", "section", "total_egg_weight", "treatment",
                         "capture_ref_values_list", "AccuracyOfDate",
                         "Observer", "RingAgeObsv", "ObserverID",
                         "Age_observed_new",
                         "pop_species_combos", "pop", "species",
                         "total_sp", "TotalEggWeight",
                         "lieu", "nic", "BoxNumber", "an", "date_ponte",
                         "grpo", "date_eclo", "pulecl", "pulenv",
                         "mort", "mbag", "fbag", "pulbag1", "pulbag14",
                         "YoungestCatch", "date_mesure", "heure", "espece",
                         "bague", "aile", "tarsed", "tarseg", "becna",
                         "poids", "obs", "dest", "orig", "TarsusRight",
                         "age_plume", "MeanEggWeight", "NEggsWeighted",
                         "date_of_capture_52", "date_of_capture_57",
                         "laying_date_minimum", "laying_date_maximum",
                         "experience", "explique", "proto",
                         "age", "FoundDead", "ObservedSex",
                         "GeneticSex", "ExperimentDescription1",
                         "ExperimentDescription2", "CaptureMethod",
                         "ChickNr", "ObservedSex", "GeneticSex",
                         "Anro", "AvgChickMass_capture", "AvgTarsus_capture",
                         "BirdStatus", "Brood_RingNr", "CaptureDateNestling",
                         "CaptureTimeNestling", "CaptureAgeNestling",
                         "Chicks", "Dead", "Delfh", "DestBoxNumber",
                         "Destination", "Dist", "FetLut", "Haapa", "Halku",
                         "Havno", "Head", "Ika", "Ip", "Jalat", "Kataja",
                         "Kk", "Kkk", "Klo", "Koe", "Koir", "Koiras",
                         "Koivu", "Kokor", "Korel", "Kork",
                         "Kpv", "Ktar", "Kukor", "Kunta", "Kunto",
                         "Kuor", "Kurel", "Kuusi", "Laji", "LastRingNumber",
                         "Latitude_Lambert", "Lent", "Leppa", "Leve", "Lihas",
                         "Lisa", "Lkoe", "LocationID_join", "LocationName",
                         "Longitude_Lambert", "Makor", "Manty", "Marel", "MassNestling",
                         "Mety", "Onil", "Opak", "Opys", "OrigBoxNumber",
                         "Paikka", "Paino", "Pun", "Puulaji", "Puut", "Pv",
                         "Rasik", "Rasika", "Reference", "Reng", "Rtapa", "Sarja",
                         "Siipi", "Sp", "Suku", "Sulsat", "Tark", "Tark2",
                         "Tila", "Tot", "Totpain", "Totrel", "Tsyy", "Tunnus",
                         "Toumi", "Value", "Vari", "Varpaat", "Vart",
                         "Vjalka", "Vkas", "Vlent", "Vnil", "Vpak", "Vpys", "Vuos", "Wb",
                         "WingLengthNestling", "X", "Y", "abr_station",
                         "chick_mass_cutoffs", "ChickAgeNestling", "Mihin",
                         "Mista", "Mkk", "Mkuor", "Mpv", "Mpy", "Mtar",
                         "Mulu", "Naaras", "Nuro", "Ojalka", "Okas", "Olent",
                         "Pajut", "Pesa", "Pihlaja", "Pitu", "Pohja",
                         "Poik", "Pontlaji", "Psulka", "Ptapa", "Tuomi",
                         "la", "lo", "ni", "nichoir", "ChickAge2", "Coordinates",
                         "ExperimentCode", "age_offspring", "bird_id",
                         "budka", "capture_method", "clutch_no", "clutch_size_error",
                         "date_ringed", "fledge_date", "fledge_date_error",
                         "fledge_number", "fledge_number_error", "hatch_date_error",
                         "hatch_number", "hatch_number_error", "lay_date_error",
                         "mass_g", "measures_taken_by", "nadmorska_vyska",
                         "nest_id", "nest_location", "nest_of_origin_id",
                         "nestbox_no", "nestbox_number", "physical_manipulation_present_at_time_of_release",
                         "physical_manipulation_present_at_time_of_catching",
                         "physiological_manipulation", "rearing_nest_id",
                         "ring_number", "sirka_delka_hddd_mm_mmm", "social_female_bird_id",
                         "social_male_bird_id", "status", "tarsus_length_mm", "time_capture",
                         "unique_nest_id", "wing_lengh_mm", "x1st_egg_lay_date",
                         "M", "fit", "x", "lower", "upper", "Warning_max", "N",
                         "CTcal", "Sex_calculated", "Sex_genetic", "Warning_max",
                         "Stage", "Logis", "BroodSize_observed", "NumberFledged_observed",
                         "ClutchSize_observed", "HatchDate_observed", "FledgeDate_observed",
                         "LayDate_observed", "IndvSpecies", "SpeciesComp",
                         "OtherSpeciesChicks", "date_time", "Site", "PLACE", "dummy_data", "where"))
